using Content.Shared.Administration;
<<<<<<< HEAD
using Content.Shared.CCVar;
=======
using Content.Shared.Mind;
using Content.Shared.Roles;
>>>>>>> 9f6826ca6b052f8cef3a47cb9281a73b2877903d
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
<<<<<<< HEAD
using Robust.Shared.Configuration;
=======
using Robust.Shared.Prototypes;
>>>>>>> 9f6826ca6b052f8cef3a47cb9281a73b2877903d

namespace Content.Client.Administration.UI.Tabs.PlayerTab;

[GenerateTypedNameReferences]
public sealed partial class PlayerTabEntry : PanelContainer
{
<<<<<<< HEAD
    public NetEntity? PlayerEntity;
=======
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
>>>>>>> 9f6826ca6b052f8cef3a47cb9281a73b2877903d

    public PlayerTabEntry(PlayerInfo player, StyleBoxFlat styleBoxFlat)
    {
        RobustXamlLoader.Load(this);
        var config = IoCManager.Resolve<IConfigurationManager>();

        var rolePrototype = player.RoleProto == null ? null : _prototype.Index(player.RoleProto.Value);

        UsernameLabel.Text = player.Username;
        if (!player.Connected)
            UsernameLabel.StyleClasses.Add("Disabled");
        JobLabel.Text = player.StartingJob;
<<<<<<< HEAD
        var separateAntagSymbols = config.GetCVar(CCVars.AdminPlayerlistSeparateSymbols);
        var genericAntagSymbol = player.Antag ? Loc.GetString("player-tab-antag-prefix") : string.Empty;
        var roleSymbol = player.Antag ? player.RoleProto.Symbol : string.Empty;
        var symbol = separateAntagSymbols ? roleSymbol : genericAntagSymbol;
        CharacterLabel.Text = Loc.GetString("player-tab-character-name-antag-symbol", ("symbol", symbol), ("name", player.CharacterName));

        if (player.Antag && config.GetCVar(CCVars.AdminPlayerlistHighlightedCharacterColor))
            CharacterLabel.FontColorOverride = player.RoleProto.Color;
        if (player.IdentityName != player.CharacterName)
            CharacterLabel.Text += $" [{player.IdentityName}]";
        RoleTypeLabel.Text = Loc.GetString(player.RoleProto.Name);
        if (config.GetCVar(CCVars.AdminPlayerlistRoleTypeColor))
            RoleTypeLabel.FontColorOverride = player.RoleProto.Color;
=======

        var colorAntags = false;
        var colorRoles = false;
        switch (colorOption)
        {
            case AdminPlayerTabColorOption.Off:
                break;
            case AdminPlayerTabColorOption.Character:
                colorAntags = true;
                break;
            case AdminPlayerTabColorOption.Roletype:
                colorRoles = true;
                break;
            default:
            case AdminPlayerTabColorOption.Both:
                colorAntags = true;
                colorRoles = true;
                break;
        }

        var symbol = string.Empty;
        switch (symbolSetting)
        {
            case AdminPlayerTabSymbolOption.Off:
                break;
            case AdminPlayerTabSymbolOption.Basic:
                symbol = player.Antag ? Loc.GetString("player-tab-antag-prefix") : string.Empty;
                break;
            default:
            case AdminPlayerTabSymbolOption.Specific:
                symbol = player.Antag ? rolePrototype?.Symbol ?? RoleTypePrototype.FallbackSymbol : string.Empty;
                break;
        }

        CharacterLabel.Text = Loc.GetString("player-tab-character-name-antag-symbol", ("symbol", symbol), ("name", player.CharacterName));

        if (player.Antag && colorAntags)
            CharacterLabel.FontColorOverride = rolePrototype?.Color ?? RoleTypePrototype.FallbackColor;
        if (player.IdentityName != player.CharacterName)
            CharacterLabel.Text += $" [{player.IdentityName}]";

        var roletype = RoleTypeLabel.Text = Loc.GetString(rolePrototype?.Name ?? RoleTypePrototype.FallbackName);
        var subtype = roles.GetRoleSubtypeLabel(rolePrototype?.Name ?? RoleTypePrototype.FallbackName, player.Subtype);
        switch (roleSetting)
        {
            case AdminPlayerTabRoleTypeOption.RoleTypeSubtype:
                RoleTypeLabel.Text = roletype != subtype
                    ? roletype + " - " +subtype
                    : roletype;
                break;
            case AdminPlayerTabRoleTypeOption.SubtypeRoleType:
                RoleTypeLabel.Text = roletype != subtype
                    ? subtype + " - " + roletype
                    : roletype;
                break;
            case AdminPlayerTabRoleTypeOption.RoleType:
                RoleTypeLabel.Text = roletype;
                break;
            default:
            case AdminPlayerTabRoleTypeOption.Subtype:
                RoleTypeLabel.Text = subtype;
                break;
        }

        if (colorRoles)
            RoleTypeLabel.FontColorOverride = rolePrototype?.Color ?? RoleTypePrototype.FallbackColor;
>>>>>>> 9f6826ca6b052f8cef3a47cb9281a73b2877903d
        BackgroundColorPanel.PanelOverride = styleBoxFlat;
        OverallPlaytimeLabel.Text = player.PlaytimeString;
        PlayerEntity = player.NetEntity;
    }
}
