#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    head: ClothingHeadHatWizard
    back: ClothingBackpack # Wizard backpack?
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    id: WizardPDA
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltWand
<<<<<<< HEAD
    # pocket1: TODO: Include wizard teleport scroll
=======
    #pocket1: WizardTeleportScroll # DeltaV - commented out until someone makes this thing not let anyone who picks it up go to Central Command
>>>>>>> 496c0c511e446e3b6ce133b750e6003484d66e30
    pocket2: WizardsGrimoire

- type: startingGear
  id: WizardRedGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed

- type: startingGear
  id: WizardVioletGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet

<<<<<<< HEAD
- type: startingGear
  id: WizardHardsuitGear
  parent: WizardVioletGear
  equipment:
    outerClothing: ClothingOuterHardsuitWizard
=======
- type: chameleonOutfit
  id: WizardChameleonOutfit
  name: roles-antag-wizard-name
  startingGear: WizardBlueGear
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLGBTPin
    gloves: ClothingHandsGlovesColorBlack
>>>>>>> 496c0c511e446e3b6ce133b750e6003484d66e30
